In [1]:
import numpy as np

# 1.1

In [68]:
x = np.random.uniform(-4,4,30)
x

array([ 2.60953638,  3.24620804,  2.65632386,  3.10061408,  3.9331767 ,
        1.11796068, -3.86850284, -0.86340214, -2.92575594,  0.3400087 ,
       -1.81196423,  3.62174267, -0.95700549,  3.08474218,  1.40606058,
       -3.88853772, -0.3454571 ,  3.08721906, -2.08940137,  2.54655656,
       -0.70313341,  3.59080391, -1.15778518,  2.1786402 ,  0.78711946,
        3.41928649, -0.86262887, -0.80684329,  1.76377927, -1.57687813])

In [25]:
x[(np.abs(x) >= 1) & (np.abs(x) <= 2)]

array([ 1.82798386, -1.87722347,  1.51118972,  1.2116036 ,  1.10971981,
       -1.11624616,  1.33583908, -1.03455018,  1.76384471,  1.65228644,
       -1.20173393])

In [7]:
np.sum(x > 0)

17

In [26]:
np.mean(np.abs(x))

2.0986564229887774

In [9]:
np.min(x)#D

-3.7242516485836097

In [10]:
np.max(x)

3.7848806984800643

In [32]:
x[np.argmin(np.abs(x))]#E

-0.3299485793944088

In [29]:
x[np.argmax(np.abs(x))]

3.7848806984800643

In [33]:
x[np.argmin(np.abs(x - 2))]#F

2.015127170101592

In [31]:
x[np.argmax(np.abs(x - 2))]

-3.7242516485836097

In [71]:
abs(x - np.trunc(x))#G

array([ 0.60953638,  0.24620804,  0.65632386,  0.10061408,  0.9331767 ,
        0.11796068,  0.86850284,  0.86340214,  0.92575594,  0.3400087 ,
        0.81196423,  0.62174267,  0.95700549,  0.08474218,  0.40606058,
        0.88853772,  0.3454571 ,  0.08721906,  0.08940137,  0.54655656,
        0.70313341,  0.59080391,  0.15778518,  0.1786402 ,  0.78711946,
        0.41928649,  0.86262887,  0.80684329,  0.76377927,  0.57687813])

In [49]:
new_max = 1#H
new_min = -1

In [50]:
((x - np.min(x)) / (np.max(x) - np.min(x)) * (new_max - new_min)) + new_min

array([ 0.65680862, -0.09595332, -0.95197042,  0.47879549, -0.50805816,
        0.39441979,  0.31462731, -1.        ,  0.76524344,  0.28749135,
       -0.64215484,  0.23150448, -0.77864959,  0.53142642, -0.30537767,
        0.52863968,  0.72473391,  0.34771649, -0.28361858,  0.15555077,
        0.16750959, -0.99009838,  1.        , -0.78028937, -0.98356572,
        0.46171251,  0.43199982,  0.76861515, -0.32814669, -0.84185916])

In [52]:
np.mean(x[(x>3) | (x<-2)] ** 2)#I

11.111989452618893

In [72]:
x = np.random.randint(-4,4,30)
x

array([-3,  0,  3, -1,  3, -3, -2,  1,  3,  0,  1, -1, -1, -4,  3,  0,  1,
        0, -4, -4, -1,  2,  1,  2, -2,  2,  2, -4, -2, -1])

In [77]:
np.where(x % 2 == 0,"parzysta","nieparzysta")#J

array(['nieparzysta', 'parzysta', 'nieparzysta', 'nieparzysta',
       'nieparzysta', 'nieparzysta', 'parzysta', 'nieparzysta',
       'nieparzysta', 'parzysta', 'nieparzysta', 'nieparzysta',
       'nieparzysta', 'parzysta', 'nieparzysta', 'parzysta', 'nieparzysta',
       'parzysta', 'parzysta', 'parzysta', 'nieparzysta', 'parzysta',
       'nieparzysta', 'parzysta', 'parzysta', 'parzysta', 'parzysta',
       'parzysta', 'parzysta', 'nieparzysta'], 
      dtype='<U11')

# K

In [80]:
np.where(x > 0,"nieujemna","ujemna")#K

array(['ujemna', 'ujemna', 'nieujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna'], 
      dtype='<U9')

In [107]:
flag = np.array(["nieujemna","ujemna"])

In [114]:
flag[(x > 0).astype('int')]

array(['nieujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'ujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'ujemna'], 
      dtype='<U9')

In [115]:
def predykat(el):
    return "ujemna" if el < 0 else "nieujemna"

In [116]:
predykat_zwektoryzowany = np.vectorize(predykat)

In [117]:
predykat_zwektoryzowany(x)

array(['ujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'nieujemna',
       'nieujemna', 'nieujemna'], 
      dtype='<U9')

# L

In [83]:
np.sum(x) / len(x)#L

-0.29999999999999999

In [85]:
np.sum((x - np.mean(x))**2) / len(x)#M

5.0766666666666662

In [90]:
np.sort(x)[0]#N

-4

In [91]:
np.sort(x)[-1]

3

In [119]:
x = np.random.uniform(-4,4,30)
x

array([ 1.68233345,  1.90077388, -2.35923027, -3.69594005, -0.50764709,
        1.86105198,  0.63544592, -1.41542624, -3.49367556,  2.6245539 ,
        2.15675928,  3.1986824 ,  3.02373353,  3.67687079, -3.90008933,
        3.38978129, -0.95070869, -2.11801913,  3.03158552,  0.25080617,
       -3.65772799, -0.8838505 ,  1.86110232,  3.46617236, -0.39020782,
       -3.055852  , -1.23109616, -1.07811959,  3.8864132 ,  0.01168337])

# O

In [130]:
np.floor(x) + 0.5

array([ 1.5,  1.5, -2.5, -3.5, -0.5,  1.5,  0.5, -1.5, -3.5,  2.5,  2.5,
        3.5,  3.5,  3.5, -3.5,  3.5, -0.5, -2.5,  3.5,  0.5, -3.5, -0.5,
        1.5,  3.5, -0.5, -3.5, -1.5, -1.5,  3.5,  0.5])

In [133]:
przedzialy = np.arange(-4,4)
print(przedzialy)
np.digitize(x,przedzialy)

[-4 -3 -2 -1  0  1  2  3]


array([6, 6, 2, 1, 4, 6, 5, 3, 1, 7, 7, 8, 8, 8, 1, 8, 4, 2, 8, 5, 1, 4, 6,
       8, 4, 1, 3, 3, 8, 5])

In [136]:
-5 + np.digitize(x,przedzialy) + 0.5

array([ 1.5,  1.5, -2.5, -3.5, -0.5,  1.5,  0.5, -1.5, -3.5,  2.5,  2.5,
        3.5,  3.5,  3.5, -3.5,  3.5, -0.5, -2.5,  3.5,  0.5, -3.5, -0.5,
        1.5,  3.5, -0.5, -3.5, -1.5, -1.5,  3.5,  0.5])

# 1.2

In [142]:
x = np.r_[1:11]
y = np.r_[10:0:-1]

In [147]:
x_ = np.mean(x)
y_ = np.mean(y)
np.sum((x-x_) * (y - y_)) / np.sqrt(np.sum((x-x_)**2)) / np.sqrt(np.sum((y - y_)**2))

-1.0

In [153]:
x = np.random.normal(size=10)
y = 5 * x + 2

In [154]:
x_ = np.mean(x)
y_ = np.mean(y)
np.sum((x-x_) * (y - y_)) / np.sqrt(np.sum((x-x_)**2)) / np.sqrt(np.sum((y - y_)**2))

0.99999999999999989

In [158]:
x = np.random.normal(size=10)
y = np.random.normal(size=10)

In [159]:
x_ = np.mean(x)
y_ = np.mean(y)
np.sum((x-x_) * (y - y_)) / np.sqrt(np.sum((x-x_)**2)) / np.sqrt(np.sum((y - y_)**2))

0.036205888351142766

# 1.3

In [160]:
def standarize(vec):
    return (vec - np.mean(vec)) / np.std(vec)
    

In [162]:
x = np.random.random(size=10)

In [166]:
np.mean(standarize(x))

-2.3314683517128288e-16

In [167]:
np.std(standarize(x))

1.0

# 1.4

In [168]:
x = np.random.normal(size=10)
y = np.random.normal(size=10)

In [169]:
np.dot(x,y)

-2.3675637129981775

# 1.5

In [172]:
np.sqrt(np.sum((y - x) * (y - x)) / x.shape[0])

1.3668882700336422

# 1.6

In [174]:
np.sum(abs(y - x)) / x.shape[0]

1.1346462618174233

# 1.7

In [175]:
np.median(abs(y - x))

1.1268744984682768

# 1.8

In [184]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)

In [185]:
x

array([1, 3, 1, 6, 6, 2, 4, 8, 0, 6])

In [188]:
np.sum(y != x) / x.shape[0]

1.0

# 1.9

In [199]:
y = np.random.randint(0,2,10)
y_ = np.random.random(10)

In [200]:
-np.sum(y * np.log(y_) + (1 - y) * np.log(1 - y_)) / y.shape[0]

1.030673602395908

# 1.10

In [224]:
def lead(x,n):
    x1 = x[n-1 : x.shape[0]]
    x_nan = np.full(n-1,np.nan)
    return np.hstack([x1,x_nan])

In [225]:
lead(np.r_[1:10],3)

array([  3.,   4.,   5.,   6.,   7.,   8.,   9.,  nan,  nan])

In [230]:
def lag(x,n):
    x1 = x[0:n+1]
    x_nan = np.full(n,np.nan)
    return np.hstack([x_nan,x1])

In [231]:
lag(np.r_[1:10],3)

array([ nan,  nan,  nan,   1.,   2.,   3.,   4.])

# 1.11

In [253]:
def cumall(x):
    if np.sum(x) == x.shape[0]:
        return x
    
    index = np.argmin(x)
    x_true = np.full(index,True,dtype=bool)
    x_false = np.full(x.shape[0] - index,False,dtype=bool)
    return np.hstack([x_true,x_false])

In [254]:
x_bool = np.array([True,True,True,False,True,False])
cumall(x_bool)

array([ True,  True,  True, False, False, False], dtype=bool)

In [259]:
def cumany(x):
    if np.sum(x) == 0:
        return x
    
    index = np.argmax(x)
    x_true = np.full(x.shape[0] - index,True,dtype=bool)
    x_false = np.full(index,False,dtype=bool)
    return np.hstack([x_false,x_true])

In [261]:
x_bool = np.array([False,False,True,True,False])
cumany(x_bool)

array([False, False,  True,  True,  True], dtype=bool)

# 1.12

In [348]:
def losuj(n,x,p):
    u = np.random.random(n)
    u = np.sort(u)
    return np.digitize(u,np.cumsum(p))
    
    

In [349]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [350]:
p = np.random.uniform(0,0.2,10)
np.cumsum(p)

array([ 0.17942834,  0.23325556,  0.24125863,  0.33997698,  0.35668407,
        0.38489977,  0.44585151,  0.57865323,  0.64187262,  0.69465106])

In [351]:
losuj(4,x,p)

array([ 6,  7, 10, 10])

# 1.13

In [405]:
x = np.sort(np.random.random(10))
y = np.random.random(10)
z = np.random.uniform(np.min(x),np.max(x),size = 20)
print(x)
print(y)
print(z)

[ 0.05484198  0.07876161  0.10211696  0.31297326  0.6046003   0.63100348
  0.76499849  0.88378648  0.9821167   0.99830487]
[ 0.77254247  0.09561933  0.91181167  0.12062665  0.1028896   0.44237753
  0.95922483  0.55589983  0.45419144  0.38821409]
[ 0.48758056  0.27679321  0.1248497   0.97920892  0.90273305  0.33301553
  0.46160713  0.99613796  0.64763756  0.9813429   0.54404983  0.35184721
  0.11957889  0.97200103  0.34448258  0.2331981   0.09488953  0.39416113
  0.60096258  0.81730127]


In [406]:
def interpolate(x,y,z):
    indexes2 = np.digitize(z,x)
    indexes1 = indexes2 - 1
    y1 = y[indexes1]
    y2 = y[indexes2]
    x1 = x[indexes1]
    x2 = x[indexes2]
    w = y1 + (y2 - y1) / (x2 - x1) * (z - x1)
    return w

In [407]:
indexes2 = np.digitize(z,x)
indexes2

array([4, 3, 3, 8, 8, 4, 4, 9, 6, 8, 4, 4, 3, 8, 4, 3, 2, 4, 4, 7])

In [408]:
interpolate(x,y,z)

array([ 0.11000686,  0.25638317,  0.82651283,  0.45719911,  0.53630234,
        0.11940766,  0.11158659,  0.39704564,  0.50653874,  0.45499182,
        0.10657234,  0.11826229,  0.84629021,  0.46465463,  0.11871022,
        0.41996278,  0.65923675,  0.11568872,  0.10311085,  0.78163937])

# 1.14

In [422]:
x = np.random.random(12).reshape(3,-1)
x

array([[ 0.47893193,  0.48741561,  0.50237369,  0.68125158],
       [ 0.35511641,  0.15732535,  0.92810862,  0.98092947],
       [ 0.75837896,  0.75859171,  0.27381868,  0.97015545]])

In [424]:
softmax = np.exp(x) / np.sum(np.exp(x),axis = 1)[:,np.newaxis]
softmax

array([[ 0.23493604,  0.23693764,  0.24050841,  0.28761792],
       [ 0.18302036,  0.15017576,  0.3245987 ,  0.34220518],
       [ 0.25960187,  0.25965711,  0.15990644,  0.32083458]])

In [425]:
np.max(softmax,axis=1)

array([ 0.28761792,  0.34220518,  0.32083458])

# 1.15

In [39]:
x = np.random.random(11)
x

array([ 0.84839161,  0.46778349,  0.26633427,  0.49858533,  0.54089225,
        0.00916554,  0.43033915,  0.77614233,  0.94532665,  0.50600807,
        0.39040927])

In [40]:
x.shape

(11,)

In [41]:
def k_windsor_aver(x,k):
    x = np.sort(x).copy()
    return (np.sum(x[3 : x.shape[0]-3]) + k * x[k] + k * x[-k-1]) / x.shape[0]
    

In [42]:
k_windsor_aver(x,3)

0.48702750191007527

# 1.16

In [114]:
import math

In [131]:
def factorial_stirling(n):
    return ((n / np.e) ** n)* np.sqrt(2*np.pi*n)

In [154]:
x = np.arange(1,10)

In [155]:
factorial_aprox = factorial_stirling(x)

In [156]:
fact_vec = np.vectorize(math.factorial)

In [157]:
factorial = fact_vec(x)

In [158]:
(factorial - factorial_aprox) / factorial

array([ 0.07786299,  0.04049782,  0.0272984 ,  0.02057604,  0.01650693,
        0.0137803 ,  0.01182622,  0.01035726,  0.00921276])

# 1.17

In [187]:
def pi_leibniz(n):
    ran = 2 * n + 1
    mian_ran = np.arange(0,2* ran)
    mian = mian_ran[mian_ran % 2 != 0]
    #licz = np.full(ran,-1,dtype='int')
    #licz = licz ** np.arange(0,ran)
    licz = np.concatenate([np.tile([1,-1],n),np.array([1])])
    
    return 4 * np.sum(licz / mian)

In [188]:
pi_leibniz(10)

3.1891847822775952

In [189]:

np.array([pi_leibniz(1000),pi_leibniz(10000),pi_leibniz(100000)])

array([ 3.1420924 ,  3.14164265,  3.14159765])

In [108]:
np.array([pi_leibniz(1000),pi_leibniz(10000),pi_leibniz(100000)]) - np.pi

array([  4.99750094e-04,   4.99975001e-05,   4.99997500e-06])

In [168]:
np.tile([1,-1],10)

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1])

# 1.18


In [110]:
n = 1000000
x = np.random.uniform(-1,1,n)
y = np.random.uniform(-1,1,n)


In [111]:
np.sum((x * x + y * y )< 1) / n * 4

3.1427719999999999

# 1.19

In [161]:
x = np.concatenate([np.arange(10),np.array([np.nan,np.nan])])
x

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  nan,
        nan])

In [162]:
np.nanmean(x)

4.5

In [165]:
np.where(np.isnan(x),np.nanmean(x),x)

array([ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. ,  4.5,
        4.5])

# 1.20

In [198]:
pi_a = np.array([np.pi])

In [199]:
pi = pi_a.astype(np.str_)[0]

In [205]:
np.array([el for el in pi if el != '.'] ).astype('int')[0:10]

array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# 1.21

In [206]:
x = np.array([1,1,1,3,4,5,6,6,6,7,7])

In [210]:
def mode(x):
    value,count = np.unique(x,return_counts=True)
    return value[np.argmax(count)]

In [211]:
mode(x)

1

# 1.22

In [214]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
y = 2 * x + 1

In [217]:
def regression(x,y):
    x_ = np.mean(x)
    y_ = np.mean(y)
    beta = np.sum((x - x_) * (y - y_)) / np.sum((x - x_) * (x - x_))
    alfa = y_ - beta * x_
    return(alfa,beta)
    

In [218]:
regression(x,y)

(1.0, 2.0)

# 1.23

In [221]:
x = np.arange(0,16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [222]:
x[::-1,:]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

# 1.24

In [223]:
x[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

# 1.25

In [395]:
p = np.random.random((10,2))
p

array([[ 0.30938418,  0.20838865],
       [ 0.25039383,  0.37904125],
       [ 0.47564913,  0.90625955],
       [ 0.6668794 ,  0.10421672],
       [ 0.69456265,  0.13474641],
       [ 0.38310929,  0.94228492],
       [ 0.57678691,  0.33753041],
       [ 0.96320006,  0.945944  ],
       [ 0.725698  ,  0.11703492],
       [ 0.24773631,  0.66199778]])

In [396]:
np.vstack([np.min(p,axis=0),np.max(p,axis=0)])

array([[ 0.24773631,  0.10421672],
       [ 0.96320006,  0.945944  ]])

# 1.26

In [475]:
X = np.random.random((5,2))
#Y = np.random.random((4,2))
Y = X
print(X)
print(Y)

[[ 0.20363229  0.66079882]
 [ 0.59059624  0.0394783 ]
 [ 0.51902868  0.75381317]
 [ 0.77475785  0.66153491]
 [ 0.23160013  0.07088747]]
[[ 0.20363229  0.66079882]
 [ 0.59059624  0.0394783 ]
 [ 0.51902868  0.75381317]
 [ 0.77475785  0.66153491]
 [ 0.23160013  0.07088747]]


In [476]:
diff= X[:,np.newaxis,:] - Y[np.newaxis,:,:]
diff.shape

(5, 5, 2)

In [477]:
diff_sqr = diff ** 2
diff_sqr.shape

(5, 5, 2)

In [478]:
dist_sqr = np.sum(diff_sqr,axis=-1)
dist_sqr

array([[ 0.        ,  0.53578029,  0.10812656,  0.32618495,  0.3487776 ],
       [ 0.53578029,  0.        ,  0.51539622,  0.42086993,  0.12986474],
       [ 0.10812656,  0.51539622,  0.        ,  0.07391268,  0.54900269],
       [ 0.32618495,  0.42086993,  0.07391268,  0.        ,  0.64388471],
       [ 0.3487776 ,  0.12986474,  0.54900269,  0.64388471,  0.        ]])

In [482]:
nearest = np.argsort(dist_sqr,axis=0)
print(nearest)

[[0 1 2 3 4]
 [2 4 3 2 1]
 [3 3 0 0 0]
 [4 2 1 1 2]
 [1 0 4 4 3]]


In [483]:
nearest.shape

(5, 5)

In [485]:
R = nearest[1,:]
R

array([2, 4, 3, 2, 1])

Spr:

In [320]:
X

array([[ 0.05478622,  0.7520336 ,  0.60188841,  0.42290965,  0.75853362],
       [ 0.56926599,  0.94830733,  0.99374519,  0.89141189,  0.01776314],
       [ 0.72155941,  0.63802674,  0.94729312,  0.25169545,  0.74577238],
       [ 0.76206189,  0.65507838,  0.23413462,  0.38543397,  0.16596017],
       [ 0.19935064,  0.02221875,  0.52742359,  0.02236218,  0.11457469],
       [ 0.81562209,  0.26069472,  0.45211555,  0.92708016,  0.71222936],
       [ 0.41424356,  0.1239543 ,  0.83234958,  0.50267501,  0.93171679]])

In [321]:
Y1 = Y[0,:]
Y1

array([ 0.71288655,  0.15907724,  0.16516459,  0.20172962,  0.08498702])

In [322]:
diff_sum = np.sum((X - Y1)**2,axis = 1)
diff_sum

array([ 1.47800661,  1.8102375 ,  1.28032674,  0.29349615,  0.44672907,
        1.02278792,  1.3430765 ])

In [323]:
diff_sum.shape

(7,)

# 1.27

In [245]:
k = 11
T = np.arange(0,k-1)
n = T.shape[0]

In [254]:
R = np.zeros([n,k-1])

In [255]:
row = np.arange(0,n)
col = T

In [256]:
row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [257]:
col

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [258]:
R[row,col] = 1

In [259]:
R

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

# 1.28

In [391]:
X = np.random.randint(-10,10,(4,4))
X

array([[  9, -10,   4,   7],
       [ -1,   3,  -4,   8],
       [ -7,  -2,  -7,   2],
       [  7,  -3,  -4,  -1]])

In [389]:
def doStochastycznej(X):
    if( np.sum(X < 0) == 0 ) | (np.sum((np.sum(X > 0,axis = 1) > 0)) != X.shape[0]):
        return np.zeros(X.shape)
    return X / np.sum(X,axis=1)[:,np.newaxis]

In [392]:
np.sum(doStochastycznej(X),axis = 1)

array([ 1.,  1.,  1.,  1.])

# 1.29

In [987]:
P = np.array([[0,0.01,0.1,0.2],
             [0.01,0.05,0.03,0.1],
             [0.1,0.03,0.05,0.01],
             [0.2,0.1,0.01,0]])
P.shape

x = np.array([2,3,4,5])
y = np.array([2,3,4,5])

In [992]:
sum_j = np.sum(P,axis = 1)
sum_j

array([ 0.31,  0.19,  0.19,  0.31])

In [993]:
sum_i = np.sum(P,axis = 0)
sum_i

array([ 0.31,  0.19,  0.19,  0.31])

In [994]:
def niezaleznosc(p):
    return np.sum(P == np.sum(P,axis = 0) * np.sum(P,axis = 1)[:,np.newaxis])!= 0

niezaleznosc(P)

False

In [995]:
EX = np.sum(x * sum_j)
EX

3.5

In [996]:
EY = np.sum(y * sum_i)
EY

3.5

In [997]:
EXkw = np.sum(x**2 * sum_j)
EXkw

13.740000000000002

In [998]:
EYkw = np.sum(y**2 * sum_i)
EYkw

13.740000000000002

In [999]:
VarX = EXkw - (EX ** 2)
VarX

1.490000000000002

In [1000]:
VarY = EYkw - EY ** 2
VarY

1.490000000000002

In [1007]:
EXY = np.sum(np.outer(x,y) * P)

In [1008]:
COV = EXY - (EX * EY)
COV

-1.1600000000000001

In [1010]:
r = COV / np.sqrt(VarX * VarY)
r

-0.778523489932885